apiVersion: v1
kind: Service
metadata:
  name: kls
  labels:
    name: kls
spec:
  type: NodePort
  ports:
  - port: 8080
    name: kls-http
    nodePort: 31020
  selector:
    name: kls
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: kls
  labels:
    name: kls
spec:
  replicas: 1
  selector:
    name: kls
  template:
    metadata:
      labels:
        name: kls
    spec:
      containers:
      - name: kls
        image: kieker/kieker-logging-server
        ports:
        - containerPort: 22
        - containerPort: 8080
        env:
          - name: KLS_JMS_HOST
            value: activemq
          - name: KLS_JMS_PORT
            value: '61616'
          - name: KLS_JMS_QUEUE
            value: kieker
