apiVersion: v1
kind: Service
metadata:
  name: kls
  labels:
    name: kls
spec:
  type: NodePort
  ports:
  - port: 8161
    name: http
    nodePort: 31010
  - port: 61616
    name: tcp
    nodePort: 31011
  - port: 61613
    name: stomp
    nodePort: 31012
  - port: 8080
    name: kls-http
    nodePort: 31020
  selector:
    name: kls
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: kls
  labels:
    name: kls
spec:
  replicas: 1
  selector:
    name: kls
  template:
    metadata:
      labels:
        name: kls
    spec:
      containers:
      - name: activemq
        image: webcenter/activemq
        ports:
        - containerPort: 8161
        - containerPort: 61616
        - containerPort: 61613
        env:
          - name: ACTIVEMQ_SERIALIZABLE_PACKAGES
            value: '*'
          - name: ACTIVEMQ_STATIC_QUEUES
            value: kieker
      - name: kieker-logging-server
        image: kieker/kieker-logging-server
        ports:
        - containerPort: 22
        - containerPort: 8080
        env:
          - name: KLS_JMS_HOST
            value: localhost
          - name: KLS_JMS_PORT
            value: '61616'
          - name: KLS_JMS_QUEUE
            value: kieker
