kind: ReplicationController
apiVersion: v1
metadata:
  name: locust-worker
  labels:
    name: locust
    role: worker
spec:
  replicas: 2
  selector:
    name: locust
    role: worker
  template:
    metadata:
      labels:
        name: locust
        role: worker
    spec:
      containers:
        - name: locust
          image: hora/recipes-rss-locust:0.2
          imagePullPolicy: Always
          env:
            - name: LOCUST_MODE
              key: LOCUST_MODE
              value: slave
            - name: MASTER_HOST
              key: MASTER_HOST
              value: locust-master
            - name: TARGET_URL
              key: TARGET_URL
              value: http://edge:9090
